# Generated by Django 2.1.3 on 2018-11-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=20)),
                ('time_pattern', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=20)),
                ('program', models.CharField(choices=[('BBA', 'BBA'), ('BScIT', 'BScIT'), ('BScIT1', 'BScIT1'), ('PCHN', 'PCHN'), ('PCCA', 'PCCA'), ('BAMJ', 'BAMJ'), ('BBA', 'BBA')], max_length=10)),
                ('semester', models.CharField(choices=[('sem1', 'sem1'), ('sem2', 'sem2'), ('sem3', 'sem3'), ('sem4', 'sem4'), ('sem5', 'sem5'), ('sem6', 'sem6'), ('sem7', 'sem7'), ('sem8', 'sem8')], max_length=10)),
                ('course', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('planned_start', models.DateTimeField(auto_now=True)),
                ('planned_end', models.DateTimeField(auto_now=True)),
                ('actual_start', models.DateTimeField(auto_now=True)),
                ('actual_end', models.DateTimeField(auto_now=True)),
                ('student_roll', models.IntegerField()),
                ('planned_sessions', models.IntegerField()),
                ('actual_sessions', models.IntegerField()),
                ('attendance', models.FloatField()),
                ('faculty', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['time_pattern'],
            },
        ),
    ]
