# Generated by Django 2.1.3 on 2018-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20181113_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='actual_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='actual_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='planned_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='planned_start_date',
            field=models.DateField(),
        ),
    ]
