# Generated by Django 2.1.3 on 2018-11-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20181113_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='actual_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
