# Generated by Django 2.1.3 on 2018-11-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20181114_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pic',
            new_name='image',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
    ]
