# Generated by Django 2.1.3 on 2018-11-20 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20181116_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_semester',
            field=models.CharField(default='sem6', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
